package com.yeelenh.manageservice.pojo;

import java.io.Serializable;

public class Customer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CustomerID
     *
     * @mbggenerated
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CustomerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.CutomerAddress
     *
     * @mbggenerated
     */
    private String cutomeraddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CustomerID
     *
     * @return the value of customer.CustomerID
     *
     * @mbggenerated
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CustomerID
     *
     * @param customerid the value for customer.CustomerID
     *
     * @mbggenerated
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CustomerName
     *
     * @return the value of customer.CustomerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CustomerName
     *
     * @param customername the value for customer.CustomerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Telephone
     *
     * @return the value of customer.Telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Telephone
     *
     * @param telephone the value for customer.Telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.CutomerAddress
     *
     * @return the value of customer.CutomerAddress
     *
     * @mbggenerated
     */
    public String getCutomeraddress() {
        return cutomeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.CutomerAddress
     *
     * @param cutomeraddress the value for customer.CutomerAddress
     *
     * @mbggenerated
     */
    public void setCutomeraddress(String cutomeraddress) {
        this.cutomeraddress = cutomeraddress == null ? null : cutomeraddress.trim();
    }

    @Override
    public String toString() {
        return "Customer{" +
                "customerid=" + customerid +
                ", customername='" + customername + '\'' +
                ", telephone='" + telephone + '\'' +
                ", cutomeraddress='" + cutomeraddress + '\'' +
                '}';
    }
}