package com.yeelenh.manageservice.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Deliverymaster implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverymaster.DeliveryID
     *
     * @mbggenerated
     */
    private String deliveryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverymaster.DeliveryProperty
     *
     * @mbggenerated
     */
    private Integer deliveryproperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverymaster.DeliveryDate
     *
     * @mbggenerated
     */
    private String deliverydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverymaster.SalesManID
     *
     * @mbggenerated
     */
    private String salesmanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverymaster.CustomerID
     *
     * @mbggenerated
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverymaster.SubTotal
     *
     * @mbggenerated
     */
    private BigDecimal subtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverymaster.DeliveryID
     *
     * @return the value of deliverymaster.DeliveryID
     *
     * @mbggenerated
     */
    public String getDeliveryid() {
        return deliveryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverymaster.DeliveryID
     *
     * @param deliveryid the value for deliverymaster.DeliveryID
     *
     * @mbggenerated
     */
    public void setDeliveryid(String deliveryid) {
        this.deliveryid = deliveryid == null ? null : deliveryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverymaster.DeliveryProperty
     *
     * @return the value of deliverymaster.DeliveryProperty
     *
     * @mbggenerated
     */
    public Integer getDeliveryproperty() {
        return deliveryproperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverymaster.DeliveryProperty
     *
     * @param deliveryproperty the value for deliverymaster.DeliveryProperty
     *
     * @mbggenerated
     */
    public void setDeliveryproperty(Integer deliveryproperty) {
        this.deliveryproperty = deliveryproperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverymaster.DeliveryDate
     *
     * @return the value of deliverymaster.DeliveryDate
     *
     * @mbggenerated
     */
    public String getDeliverydate() {
        return deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverymaster.DeliveryDate
     *
     * @param deliverydate the value for deliverymaster.DeliveryDate
     *
     * @mbggenerated
     */
    public void setDeliverydate(String deliverydate) {
        this.deliverydate = deliverydate == null ? null : deliverydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverymaster.SalesManID
     *
     * @return the value of deliverymaster.SalesManID
     *
     * @mbggenerated
     */
    public String getSalesmanid() {
        return salesmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverymaster.SalesManID
     *
     * @param salesmanid the value for deliverymaster.SalesManID
     *
     * @mbggenerated
     */
    public void setSalesmanid(String salesmanid) {
        this.salesmanid = salesmanid == null ? null : salesmanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverymaster.CustomerID
     *
     * @return the value of deliverymaster.CustomerID
     *
     * @mbggenerated
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverymaster.CustomerID
     *
     * @param customerid the value for deliverymaster.CustomerID
     *
     * @mbggenerated
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverymaster.SubTotal
     *
     * @return the value of deliverymaster.SubTotal
     *
     * @mbggenerated
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverymaster.SubTotal
     *
     * @param subtotal the value for deliverymaster.SubTotal
     *
     * @mbggenerated
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    @Override
    public String toString() {
        return "Deliverymaster{" +
                "deliveryid='" + deliveryid + '\'' +
                ", deliveryproperty=" + deliveryproperty +
                ", deliverydate='" + deliverydate + '\'' +
                ", salesmanid='" + salesmanid + '\'' +
                ", customerid=" + customerid +
                ", subtotal=" + subtotal +
                '}';
    }
}