package com.yeelenh.manageservice.pojo;

import java.io.Serializable;

public class Deliverydetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverydetail.DeliveryID
     *
     * @mbggenerated
     */
    private String deliveryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverydetail.ProductID
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverydetail.SalesQuantity
     *
     * @mbggenerated
     */
    private Integer salesquantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliverydetail.SalesPrice
     *
     * @mbggenerated
     */
    private Double salesprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverydetail.DeliveryID
     *
     * @return the value of deliverydetail.DeliveryID
     *
     * @mbggenerated
     */
    public String getDeliveryid() {
        return deliveryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverydetail.DeliveryID
     *
     * @param deliveryid the value for deliverydetail.DeliveryID
     *
     * @mbggenerated
     */
    public void setDeliveryid(String deliveryid) {
        this.deliveryid = deliveryid == null ? null : deliveryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverydetail.ProductID
     *
     * @return the value of deliverydetail.ProductID
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverydetail.ProductID
     *
     * @param productid the value for deliverydetail.ProductID
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverydetail.SalesQuantity
     *
     * @return the value of deliverydetail.SalesQuantity
     *
     * @mbggenerated
     */
    public Integer getSalesquantity() {
        return salesquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverydetail.SalesQuantity
     *
     * @param salesquantity the value for deliverydetail.SalesQuantity
     *
     * @mbggenerated
     */
    public void setSalesquantity(Integer salesquantity) {
        this.salesquantity = salesquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliverydetail.SalesPrice
     *
     * @return the value of deliverydetail.SalesPrice
     *
     * @mbggenerated
     */
    public Double getSalesprice() {
        return salesprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliverydetail.SalesPrice
     *
     * @param salesprice the value for deliverydetail.SalesPrice
     *
     * @mbggenerated
     */
    public void setSalesprice(Double salesprice) {
        this.salesprice = salesprice;
    }

    @Override
    public String toString() {
        return "Deliverydetail{" +
                "deliveryid='" + deliveryid + '\'' +
                ", productid='" + productid + '\'' +
                ", salesquantity=" + salesquantity +
                ", salesprice=" + salesprice +
                '}';
    }
}