package com.yeelenh.manageservice.pojo;

public class Losespill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losespill.LoseSpillID
     *
     * @mbggenerated
     */
    private String losespillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losespill.ProductID
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losespill.CheckDate
     *
     * @mbggenerated
     */
    private String checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losespill.Counts
     *
     * @mbggenerated
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column losespill.Flags
     *
     * @mbggenerated
     */
    private Integer flags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losespill.LoseSpillID
     *
     * @return the value of losespill.LoseSpillID
     *
     * @mbggenerated
     */
    public String getLosespillid() {
        return losespillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losespill.LoseSpillID
     *
     * @param losespillid the value for losespill.LoseSpillID
     *
     * @mbggenerated
     */
    public void setLosespillid(String losespillid) {
        this.losespillid = losespillid == null ? null : losespillid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losespill.ProductID
     *
     * @return the value of losespill.ProductID
     *
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losespill.ProductID
     *
     * @param productid the value for losespill.ProductID
     *
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losespill.CheckDate
     *
     * @return the value of losespill.CheckDate
     *
     * @mbggenerated
     */
    public String getCheckdate() {
        return checkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losespill.CheckDate
     *
     * @param checkdate the value for losespill.CheckDate
     *
     * @mbggenerated
     */
    public void setCheckdate(String checkdate) {
        this.checkdate = checkdate == null ? null : checkdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losespill.Counts
     *
     * @return the value of losespill.Counts
     *
     * @mbggenerated
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losespill.Counts
     *
     * @param counts the value for losespill.Counts
     *
     * @mbggenerated
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column losespill.Flags
     *
     * @return the value of losespill.Flags
     *
     * @mbggenerated
     */
    public Integer getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column losespill.Flags
     *
     * @param flags the value for losespill.Flags
     *
     * @mbggenerated
     */
    public void setFlags(Integer flags) {
        this.flags = flags;
    }
}