package com.yeelenh.manageservice.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Purchasemaster  implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasemaster.PurchaseID
     *
     * @mbggenerated
     */
    private String purchaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasemaster.PurchaseDate
     *
     * @mbggenerated
     */
    private String purchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasemaster.SupplierID
     *
     * @mbggenerated
     */
    private String supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasemaster.PurchaseProperty
     *
     * @mbggenerated
     */
    private Integer purchaseproperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchasemaster.SubTotal
     *
     * @mbggenerated
     */
    private BigDecimal subtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasemaster.PurchaseID
     *
     * @return the value of purchasemaster.PurchaseID
     *
     * @mbggenerated
     */
    public String getPurchaseid() {
        return purchaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasemaster.PurchaseID
     *
     * @param purchaseid the value for purchasemaster.PurchaseID
     *
     * @mbggenerated
     */
    public void setPurchaseid(String purchaseid) {
        this.purchaseid = purchaseid == null ? null : purchaseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasemaster.PurchaseDate
     *
     * @return the value of purchasemaster.PurchaseDate
     *
     * @mbggenerated
     */
    public String getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasemaster.PurchaseDate
     *
     * @param purchasedate the value for purchasemaster.PurchaseDate
     *
     * @mbggenerated
     */
    public void setPurchasedate(String purchasedate) {
        this.purchasedate = purchasedate == null ? null : purchasedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasemaster.SupplierID
     *
     * @return the value of purchasemaster.SupplierID
     *
     * @mbggenerated
     */
    public String getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasemaster.SupplierID
     *
     * @param supplierid the value for purchasemaster.SupplierID
     *
     * @mbggenerated
     */
    public void setSupplierid(String supplierid) {
        this.supplierid = supplierid == null ? null : supplierid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasemaster.PurchaseProperty
     *
     * @return the value of purchasemaster.PurchaseProperty
     *
     * @mbggenerated
     */
    public Integer getPurchaseproperty() {
        return purchaseproperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasemaster.PurchaseProperty
     *
     * @param purchaseproperty the value for purchasemaster.PurchaseProperty
     *
     * @mbggenerated
     */
    public void setPurchaseproperty(Integer purchaseproperty) {
        this.purchaseproperty = purchaseproperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchasemaster.SubTotal
     *
     * @return the value of purchasemaster.SubTotal
     *
     * @mbggenerated
     */
    public BigDecimal getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchasemaster.SubTotal
     *
     * @param subtotal the value for purchasemaster.SubTotal
     *
     * @mbggenerated
     */
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    @Override
    public String toString() {
        return "Purchasemaster{" +
                "purchaseid='" + purchaseid + '\'' +
                ", purchasedate='" + purchasedate + '\'' +
                ", supplierid='" + supplierid + '\'' +
                ", purchaseproperty=" + purchaseproperty +
                ", subtotal=" + subtotal +
                '}';
    }
}