package com.yeelenh.manageservice.pojo;

import java.io.Serializable;

public class Users implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UserID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PasswordCode
     *
     * @mbggenerated
     */
    private String passwordcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UserAuthority
     *
     * @mbggenerated
     */
    private Integer userauthority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UserID
     *
     * @return the value of users.UserID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UserID
     *
     * @param userid the value for users.UserID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UserName
     *
     * @return the value of users.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UserName
     *
     * @param username the value for users.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PasswordCode
     *
     * @return the value of users.PasswordCode
     *
     * @mbggenerated
     */
    public String getPasswordcode() {
        return passwordcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.PasswordCode
     *
     * @param passwordcode the value for users.PasswordCode
     *
     * @mbggenerated
     */
    public void setPasswordcode(String passwordcode) {
        this.passwordcode = passwordcode == null ? null : passwordcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UserAuthority
     *
     * @return the value of users.UserAuthority
     *
     * @mbggenerated
     */
    public Integer getUserauthority() {
        return userauthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UserAuthority
     *
     * @param userauthority the value for users.UserAuthority
     *
     * @mbggenerated
     */
    public void setUserauthority(Integer userauthority) {
        this.userauthority = userauthority;
    }

    @Override
    public String toString() {
        return "Users{" +
                "userid='" + userid + '\'' +
                ", username='" + username + '\'' +
                ", passwordcode='" + passwordcode + '\'' +
                ", userauthority=" + userauthority +
                '}';
    }
}