package com.yeelenh.manageservice.mapper;

import com.yeelenh.manageservice.pojo.Deliverydetail;

import java.util.List;

public interface DeliverydetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverydetail
     *
     * @mbggenerated
     */
    int insert(Deliverydetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverydetail
     *
     * @mbggenerated
     */
    int insertSelective(Deliverydetail record);
    List<Deliverydetail> selectDeliverydetailByCustomerID(String customerid);
    List<Deliverydetail> getAllDeliveryByDeliveryID(String deliveryid);
    List<Deliverydetail> getDeliverydetailByProductId(String productid);
}