package com.yeelenh.manageservice.mapper;

import com.yeelenh.manageservice.pojo.Deliverymaster;

public interface DeliverymasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverymaster
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String deliveryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverymaster
     *
     * @mbggenerated
     */
    int insert(Deliverymaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverymaster
     *
     * @mbggenerated
     */
    int insertSelective(Deliverymaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverymaster
     *
     * @mbggenerated
     */
    Deliverymaster selectByPrimaryKey(String deliveryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverymaster
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Deliverymaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliverymaster
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Deliverymaster record);
}