package com.yeelenh.manageservice.mapper;

import com.yeelenh.manageservice.pojo.Losespill;

public interface LosespillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losespill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String losespillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losespill
     *
     * @mbggenerated
     */
    int insert(Losespill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losespill
     *
     * @mbggenerated
     */
    int insertSelective(Losespill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losespill
     *
     * @mbggenerated
     */
    Losespill selectByPrimaryKey(String losespillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losespill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Losespill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table losespill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Losespill record);
}