package com.yeelenh.manageservice.mapper;

import com.yeelenh.manageservice.pojo.Purchasedetail;

import java.util.List;

public interface PurchasedetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int insert(Purchasedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchasedetail
     *
     * @mbggenerated
     */
    int insertSelective(Purchasedetail record);
    List<Purchasedetail> selectAllByPurchaseId(String id);
}